name: Update Download Links

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Get latest release info
      id: release
      uses: actions/github-script@v7
      with:
        script: |
          const { data: releases } = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
          });
          
          const latestRelease = releases[0];
          const assets = latestRelease.assets;
          
          // Find assets by platform
          const windowsAsset = assets.find(asset => 
            asset.name.includes('.exe') || 
            asset.name.toLowerCase().includes('windows') ||
            asset.name.toLowerCase().includes('win')
          );
          
          const macAsset = assets.find(asset => 
            asset.name.includes('.dmg') || 
            asset.name.toLowerCase().includes('mac') ||
            asset.name.toLowerCase().includes('darwin')
          );
          
          const linuxAsset = assets.find(asset => 
            asset.name.includes('.AppImage') || 
            asset.name.toLowerCase().includes('linux')
          );
          
          return {
            windows_url: windowsAsset ? windowsAsset.browser_download_url : '',
            mac_url: macAsset ? macAsset.browser_download_url : '',
            linux_url: linuxAsset ? linuxAsset.browser_download_url : '',
            version: latestRelease.tag_name
          };
          
    - name: Update _config.yml
      run: |
        cat > docs/_config.yml << 'EOF'
        title: SASIE
        logo: /assets/img/logo.png
        description: SASIE is the Supplementary Alerting System Interface Extension.
        show_downloads: true
        theme: jekyll-theme-minimal
        
        # Latest release download URLs
        latest_release:
          windows_url: ${{ fromJson(steps.release.outputs.result).windows_url }}
          mac_url: ${{ fromJson(steps.release.outputs.result).mac_url }}
          linux_url: ${{ fromJson(steps.release.outputs.result).linux_url }}
          version: ${{ fromJson(steps.release.outputs.result).version }}
        EOF
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/_config.yml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update download links for release ${{ fromJson(steps.release.outputs.result).version }}"
          git push
        fi